do "COVID-19 vaccine health impacts and values_sureg_means.do"
/*
inputs: 
unpaid_work_loss_nonfatal_case.dta
no_cont_2_lags_death_pfizer_v_other_overall.dta 
no_cont_2_lags_infections_pfizer_v_other_overall.dta
direct_costs_current_2019USD.dta
qaly_losses_per_nonfatal_case.dta
qaly_losses_per_fatal_case.dta
no_cont_2_lags_death_pfizer_v_other_pfz.dta 
no_cont_2_lags_infections_pfizer_v_other_pfz.dta
no_cont_2_lags_gdp_pfizer_v_other_overall_quarterly_gdp.dta 
no_cont_2_lags_gdp_pfizer_v_other_pfz.dta 
overall_annual_gdp.dta
pfz_annual_gdp.dta 
full_income.dta
outputs:
indirect_costs_nonfatal_case.dta 
*/

do "COVID-19 vaccine health impacts and values_sureg_novax.do"
/*
inputs: 
no_cont_2_lags_death_pfizer_v_other_overall.dta 
no_cont_2_lags_infections_pfizer_v_other_overall.dta
indirect_costs_nonfatal_case.dta
direct_costs_current_2019USD.dta
qaly_losses_per_nonfatal_case.dta
qaly_losses_per_fatal_case.dta
no_cont_2_lags_death_pfizer_v_other_pfz.dta 
no_cont_2_lags_infections_pfizer_v_other_pfz.dta
no_cont_2_lags_gdp_pfizer_v_other_overall_quarterly_gdp.dta 
no_cont_2_lags_gdp_pfizer_v_other_pfz.dta 
overall_annual_gdp.dta
pfz_annual_gdp.dta 
full_income.dta
*/

do "COVID-19 vaccine health impacts and values_sureg_pandemic.do"
/*
inputs: 
no_cont_2_lags_death_pfizer_v_other_overall.dta  
no_cont_2_lags_infections_pfizer_v_other_overall.dta
indirect_costs_nonfatal_case.dta
direct_costs_current_2019USD.dta
qaly_losses_per_nonfatal_case.dta
qaly_losses_per_fatal_case.dta
no_cont_2_lags_gdp_pfizer_v_other_overall_quarterly_gdp.dta 
overall_annual_gdp.dta
full_income.dta
*/

do "COVID-19 vaccine health impacts and values_sureg_predicted.do"
/*
inputs: 
no_cont_2_lags_death_pfizer_v_other_overall.dta 
no_cont_2_lags_infections_pfizer_v_other_overall.dta
indirect_costs_nonfatal_case.dta
direct_costs_current_2019USD.dta
qaly_losses_per_nonfatal_case.dta
qaly_losses_per_fatal_case.dta
no_cont_2_lags_gdp_pfizer_v_other_overall_quarterly_gdp.dta 
overall_annual_gdp.dta
full_income.dta
*/

